name: Test and Lint

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[lint]'
    - name: Lint with ruff
      run: ruff check .
    - name: Format with ruff
      run: ruff format --check .
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.'
    - name: Run test
      run: python3 -m unittest
  tag:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.'
    - name: Check and push
      if: ${{ github.event_name == 'push' }}
      run: |
        VERSION="$(pip show harp-logfmt-python | grep Version | awk '{print $2}')"
        if [ ! $(git tag -l "$VERSION") ];
        then
          git tag "$VERSION"
          git push origin "$VERSION"
        fi
